### ISSUE TITLE
Support comments in markdown

### ISSUE THREAD

**Issue by vi** [maghoff/sausagewiki#54]
Typically it is `<!-- HTML comments -->`.

Or maybe better entire sanitized inline HTML should be supported so that other Markdown documents can be copied and pasted into the wiki.

**Comment by maghoff** [comment]
Hi :) Thanks for your interest. I have added a document describing the high-level design of Sausagewiki: https://github.com/maghoff/sausagewiki/blob/master/DESIGN.md

As per the design document, embedded HTML is out of the question. Inline comments also feel exclusively like a content producer feature, while Sausagewiki is meant for collaborative editing.

I am closing this issue because it is not in line with the design goals for Sausagewiki.

**Comment by vi** [comment]
Then there should be another "notice to editors, but not to readers" feature, which should also point to exact piece of source text.

Such comments are often used to prevent repeated seemingly useful, but actually wrong edits.

Easiest way is to just support `<!-- ... -->` syntax without supporting the rest of HTML things.
