### ISSUE TITLE
UI: Theming, accessibility and per-page colors

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#71]
Hey, i really like the new themes.

However i don't understand why the theme **has** to change on every page. It is very pretty, but also confusing and not very useful. And however, it is not very appropriate for people with cognitive issues (sight and/or image processing).

I have different ideas on how to address this issue : 
- disable theming altogether (not my favorite option)
- have a cli option or a config file to force site-wide theme (probably not your favorite option given sausagewiki's minimalist ambition)
- conceive a proper theming system, like for instance an optional stylesheet on runtime to replace the internal one

Customization is a common issue. Considering a proper theming system would also "solve" #65 for me because i could have my CSS customization without maintaining a fork of sausagewiki :)

What are your thoughts on this?

**Comment by maghoff** [comment]
I'm sorry you experience this as problematic. Sausagewiki, and especially the brand new styling, is a work in progress that I do in the open. Perhaps you will like it better in the future. Perhaps not. I'm not inclined to explain all my reasoning as I go, since that would add a considerable overhead to my effort.

I have just explained my thoughts on style customization here: https://github.com/maghoff/sausagewiki/issues/67#issuecomment-399770510
