### ISSUE TITLE
2021-05-01 release, any changes/new features of note?

### ISSUE THREAD

**Issue by kevjonesin** [maghoff/sausagewiki#75]
Hi, thanks for sharing Sausagewiki with us.
I noticed that a new release has occurred. Anything of note in it? Changes/features/bug-fixes?
Tnx again, ltr.

**Comment by maghoff** [comment]
No meaningful release has happened. I use GitHub releases to publish build output from by continuous build setup. It's a bit unfortunate that it causes notifications that a new release has been published.

The only change since the last time is that I have run `cargo update` to update my dependencies so the build won't fail with the upcoming release of Rust.
